#!/bin/bash

# display the contents of file /etc/passwd

file="/etc/passwd"

while IFS=: read -r username uid info home shell; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < "$file"

