#!/usr/bin/env bash
# Display the time for 12:59
# display hours from 0 to 12
# display minutes from 1 to 59
hour=0
while [ $hour -le 12 ]


   echo "Hour": $hours"
  minute=1
 while [ $minute -le 59 ]
 do
  echo "$minute"
 (( minute++ ))
done

