#!/usr/bin/env bash
# Display the time for 12:59
# display hours from 0 to 12
# display minutes from 1 to 59
hour=0

while true; 
do
 [ $hour -le 12 ]
   echo "Hour ; hour"
  minute=1
  echo $minute
 (( minute++ ))
done
