#!/usr/bin/env bash
# Displays information about the file "school".
if

 echo "school file exist"
 if [ -s "school" ]
 then
  echo "school file is not empty"
else
 echo "school file is empty"
 fi
 
 then
 echo "school is a regular file"
 else
 echo "school file does not exist"
 fi
 ^c

