#!/usr/bin/env bash
# Gives you information about the school file.
File [ "school" ]
 if file has the name "school"
 then
 echo "school file exist"
 if  "file doesn't not exist"
 then
  echo " school file does not exist"
 
 echo "school file is empty"
 fi
 if the file is not empty
 then
 echo " school file is not empty"
 fi
 else
 echo "school is a regular file"
 fi

